"""заново делаю

Revision ID: 84e30ca74187
Revises: b9fa3ef4ce5f
Create Date: 2024-11-26 00:19:29.228288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84e30ca74187"
down_revision = "b9fa3ef4ce5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="Идентификатор вакансии"
        ),
        sa.Column("user_id", sa.String(), nullable=True, comment="Идентификатор пользователя"),
        sa.Column("title", sa.String(), nullable=True, comment="Название вакансии"),
        sa.Column("discription", sa.String(), nullable=True, comment="описание вакансии"),
        sa.Column("salary_from", sa.Integer(), nullable=True, comment="Зарплата от"),
        sa.Column("salary_to", sa.Integer(), nullable=True, comment="Зарплата до"),
        sa.Column("is_active", sa.Boolean(), nullable=True, comment="Активна ли вакансия"),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="Дата создания записи"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "responses",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="Идентификатор отклика"
        ),
        sa.Column("user_id", sa.String(), nullable=True, comment="Идентификатор пользователя"),
        sa.Column("job_id", sa.Integer(), nullable=True, comment="Идентификатор вакансии"),
        sa.Column("message", sa.String(), nullable=True, comment="Сопроводительное письмо"),
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="Дата создания записи"),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("responses")
    op.drop_table("jobs")
    # ### end Alembic commands ###
