
FROM python:3.11 as rumti
WORKDIR /app
COPY ./src .
# COPY ./labor_exchange .
# ENV MY_ENV=.env
# COPY .env .env
RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt
# RUN pip install httptools
# RUN pip install python-keycloak
